version: "2"

build:
  commands:
    - echo "Building Cloudflare Worker Docker container"

deploy:
  healthcheckPath: "/"
  healthcheckTimeout: 100
  restartPolicyType: on-failure
  restartPolicyMaxRetries: 10

environments:
  production:
    CLOUDFLARE_API_TOKEN: ${{CLOUDFLARE_API_TOKEN}}
    CLOUDFLARE_ACCOUNT_ID: ${{CLOUDFLARE_ACCOUNT_ID}}
  
experimental:
  incrementalBuild: true
