name = "names-api"
main = "index.js"
compatibility_date = "2024-08-06"

# Deploy to workers.dev subdomain
workers_dev = true

# D1 Database configuration
[[d1_databases]]
binding = "NAMES_DB"
database_name = "names_db"
database_id = "f7cf8f63-f923-495c-be8a-0312766fb2e1"

# Database migrations
[[migrations]]
tag = "v1"
new_classes = ["names_db"]
